// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyfxyjtllczmzjnbhliq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5Znh5anRsbGN6bXpqbmJobGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NTkxNjgsImV4cCI6MjA3NzIzNTE2OH0.CxbTj3wX9kwOyiCOQsvYevN2AGdpOrfFeNqVaqkd7Ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});